# Generated by Django 3.2.14 on 2022-07-28 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0002_auto_20220728_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date(2022, 7, 28))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.course')),
            ],
        ),
    ]
