# Generated by Django 3.2.14 on 2022-07-27 17:50

import Curso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=Curso.models.upload_to)),
                ('state', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE'), (2, 'FULL')])),
            ],
        ),
    ]
