# Generated by Django 3.2.14 on 2022-07-28 02:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='capacity',
            new_name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='state',
        ),
        migrations.AddField(
            model_name='course',
            name='actual_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=django_fsm.FSMIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
