# Generated by Django 3.2.14 on 2022-07-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pedro', max_length=30, verbose_name='Nombres')),
                ('lastName', models.CharField(default='Cordero', max_length=30, verbose_name='Apellido')),
                ('idNumber', models.CharField(default='0105913891', max_length=10, verbose_name='Cedula')),
                ('email', models.EmailField(default='pedro@ups.edu.ec', max_length=50, verbose_name='Correo')),
                ('academicTitle', models.CharField(default='Ingeniero de Sistemas', max_length=100, verbose_name='Titulo academico')),
                ('telephone', models.CharField(default='0987654321', max_length=10, verbose_name='Telefono')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
