# Generated by Django 3.2.14 on 2022-07-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='idNumber',
            field=models.CharField(default='0105913881', max_length=10, verbose_name='Cedula'),
        ),
    ]
